{% set name = "pertpy" %}
{% set version = "0.11.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pertpy-{{ version }}.tar.gz
  sha256: 60681d1ebe1cb2cbecdd4ab7f9cbb3c9c6e304af67ad2267e550edda7a3a9d2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - rich
    - scanpy
    - mudata
    - requests
    - scikit-misc
    - scvi-tools
    - adjusttext
    - ott-jax
    - sparsecca
    - openpyxl
    - pubchempy
    - pyarrow
    - blitzgsea
    - scikit-learn >=1.4
    - fast-array-utils
    - lamin_utils
    - arviz

test:
  imports:
    - pertpy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pertpy.readthedocs.io
  summary: Perturbation Analysis in the scverse ecosystem.
  dev_url: https://github.com/scverse/pertpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mschilli87
    - Zethson
